users:
  - user:
      # 登陆账号：邮箱或者手机号:字符串
      username: ''
      # 账号密码：字符串
      password: ''
      # 班级，请自行打开批改网，看看自己的班级全称：字符串
      class_name:
      # 作文号，支持多篇作文并发，pids len ∈[1,∞）List[str]
      pids: [ '2283917' ]

#  - user:
#      username: ''
#      password: ''
#      class_name:
#      pids: [ '' ]